"""Explicit cleanup for a completed Flight2World run.

Only the reproducibly regenerable ODM intermediates identified by the storage audit
are ever removed:

  odm_projects/<name>/opensfm/
  odm_projects/<name>/openmvs/
  odm_projects/<name>/odm_filterpoints/
  odm_projects/<name>/odm_meshing/

The command is explicit (`python -m sih3d cleanup --name <run> --yes`);
without `--yes` it is a dry-run.  It verifies the run/project exists and,
if a `report.json` is present, that it is marked successful.  Missing
deletable directories are tolerated.  Protected paths (video, telemetry,
frames, final LAZs, mesh, viewer, report.json, coords.txt, reconstruction.json
outside the deletable intermediates) are never touched – we simply never
enumerate them.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

# Exactly the intermediates the audit identified as safe and reproducible.
# They are all inside odm_projects/<name>/ and can be regenerated by re-running ODM.
DELETABLE_SUBDIRS = [
    "opensfm",
    "openmvs",
    "odm_filterpoints",
    "odm_meshing",
]

# Final / protected artefacts that must never be deleted – documented here for
# auditability, but the implementation never enumerates them anyway.
PROTECTED_NOTE = (
    "Never deleted: original video/telemetry, data/runs/<name>/frames, "
    "final LAZs (odm_georeferenced_model.laz, sih3d_*.laz), "
    "odm_texturing/, viewer/data/, report.json, keyframes.json, "
    "coords.txt, reconstruction.json (if still required)."
)


def _dir_size(path: Path) -> int:
    total = 0
    try:
        for p in path.rglob("*"):
            if p.is_file():
                try:
                    total += p.stat().st_size
                except OSError:
                    pass
    except OSError:
        pass
    return total


def _human_size(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KB"
    if n < 1024 * 1024 * 1024:
        return f"{n / 1024 / 1024:.1f} MB"
    return f"{n / 1024 / 1024 / 1024:.2f} GB"


def is_run_successful(work_dir: Path, project_dir: Path) -> tuple[bool, str]:
    """Return (successful, reason).  Checks report.json if present.

    Successful if:
      - work_dir/report.json exists and reconstruction.ok is true, OR
      - report.json has outputs, OR
      - final cloud exists (odm_georeferencing/odm_georeferenced_model.laz or sih3d_*.laz)
    If no report and no final cloud, not successful.
    """
    report_path = work_dir / "report.json"
    if report_path.exists():
        try:
            data = json.loads(report_path.read_text())
            rec = data.get("reconstruction", {})
            if rec.get("ok") is True:
                return True, "report.json marks reconstruction ok"
            if data.get("outputs"):
                return True, "report.json has outputs"
            # Some successful runs may have empty reconstruction but classified outputs
            # still considered successful if report was written after viewer export.
            # Fall through to file checks.
        except Exception as e:
            return False, f"report.json unreadable: {e}"
        # report exists but not clearly successful – check final files as fallback
    # Fallback: check for final cloud / mesh existence as success marker
    for rel in [
        "odm_georeferencing/odm_georeferenced_model.laz",
        "sih3d_classified.laz",
        "sih3d_filled.laz",
        "sih3d_final.laz",
        "odm_georeferencing/coords.txt",
    ]:
        if (project_dir / rel).exists():
            return True, f"found {rel}"
    if report_path.exists():
        return False, "report.json does not mark successful completion"
    return False, "no report.json and no final outputs found"


def get_deletable_paths(project_dir: Path) -> list[Path]:
    """Return existing deletable subdirectories inside project_dir.

    Only the four audit-approved intermediates.  Missing directories are ignored.
    Paths are guaranteed to be children of project_dir (no traversal).
    """
    out: list[Path] = []
    project_resolved = project_dir.resolve()
    for name in DELETABLE_SUBDIRS:
        p = project_dir / name
        # safety: ensure p is inside project_dir
        try:
            # resolve without requiring existence
            p_resolved = p.resolve()
            # For non-existing paths, resolve may not exist; check relative
            # Use simple check: project_dir in parents
            if project_resolved not in p_resolved.parents and p_resolved != project_resolved:
                # Fallback string containment check for non-existing paths on some platforms
                if not str(p_resolved).startswith(str(project_resolved)):
                    continue
        except Exception:
            # If resolve fails, fall back to string check
            if not str(p.resolve()).startswith(str(project_resolved)):
                continue
        if p.exists() and p.is_dir():
            out.append(p)
    return out


def collect_cleanup_info(project_dir: Path) -> tuple[list[Path], int, list[tuple[Path, int]]]:
    """Return (deletable_paths, total_bytes, [(path, bytes), ...])."""
    paths = get_deletable_paths(project_dir)
    sized = [(p, _dir_size(p)) for p in paths]
    total = sum(s for _, s in sized)
    return paths, total, sized


def run_cleanup(
    work_root: Path | str,
    projects_root: Path | str,
    name: str,
    confirm: bool = False,
) -> dict:
    """Perform (or dry-run) cleanup for a run.

    Returns a dict with keys:
      work_dir, project_dir, deletable, total_bytes, sized, dry_run, deleted, error

    Does not raise on missing deletable dirs; raises SystemExit on missing
    project/run or unsuccessful run (so CLI can show a clear message).
    The caller may catch SystemExit for programmatic use.
    """
    work_root = Path(work_root)
    projects_root = Path(projects_root)
    work_dir = work_root / name
    project_dir = projects_root / name

    # 1. Verify existence
    if not work_dir.exists() and not project_dir.exists():
        raise SystemExit(f"Run/project '{name}' not found in {work_root} nor {projects_root}")
    if not project_dir.exists():
        raise SystemExit(f"Project directory not found: {project_dir}")
    # work_dir may legitimately be absent for externally prepared projects, but
    # if present we check it; if absent we still allow cleanup based on project.

    # 2. Verify successful completion if report available
    successful, reason = is_run_successful(work_dir, project_dir)
    if not successful:
        raise SystemExit(
            f"Refusing cleanup: run '{name}' not marked successful ({reason}). "
            f"Check {work_dir / 'report.json'} or ensure final outputs exist."
        )

    # 3. Collect what will be deleted
    deletable = get_deletable_paths(project_dir)
    sized = [(p, _dir_size(p)) for p in deletable]
    total = sum(s for _, s in sized)

    result = {
        "work_dir": str(work_dir),
        "project_dir": str(project_dir),
        "deletable": [str(p) for p in deletable],
        "sized": [(str(p), s) for p, s in sized],
        "total_bytes": total,
        "dry_run": not confirm,
        "deleted": [],
        "error": None,
    }

    if not confirm:
        return result

    # 5 & 7. Actually delete, handling already-missing gracefully
    deleted: list[str] = []
    for p in deletable:
        try:
            if p.exists():
                shutil.rmtree(p)
                deleted.append(str(p))
        except OSError as e:
            result["error"] = str(e)
            # continue with others
    result["deleted"] = deleted
    result["dry_run"] = False
    return result
